import Head from 'next/head'
import Image from 'next/image';
import styles from '@/styles/Home.module.css'
import { useState } from 'react';
import Api from "./api/index";
import Search from '@/images/search';



export default function Home() {
const [pos, setPos] = useState()
console.log(pos);
  const submitContact = async (event) => {
    event.preventDefault();
    const url =  Api();
    const data = await fetch(url + `&s=${event.target.name.value}`);
    const json = await data.json();
    setPos(json.Search)
    // console.log(json.Search);
  };


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles['container-image']}>
          <div className={styles['header-home']}>
            <h1>logo</h1>
            <div>
            <form onSubmit={submitContact} className={styles.form}>
                <input
                  className={styles.input}
                  id="name"
                  name="name"
                  type="text"
                  autocomplete="name"
                  required
                />
                <button type="submit" style={{borderWidth: 0, width: 50,height: 50,padding: 3,borderColor: 'transparent'}}>
                  <Search/>
                </button>
            </form>
            </div>
            <h1>profil</h1>
          </div>
          <div className={styles.title}>
            <h1 style={{fontSize: 70, paddingBottom: 20}}>It</h1>
            <p style={{fontSize: 25}}>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
          </div>
        </div>
        <section style={{backgroundColor: 'grey', padding: '20px 30px',zIndex: 999, marginBottom: 80}}>
          <ul style={{display:'flex',justifyContent: 'space-around',listStyle: 'none'}}>
            <li>ALL MOVIE</li>
            <li>ACTION</li>
            <li>ROMANCE</li>
            <li>FAMILY</li>
          </ul>
        </section>
        <section className={styles.hero}>
          {pos && pos.map((e, i) =>{
            return(
              <div className={styles.card} style={{borderRadius: 20,backgroundImage: `url(${e.Poster})`,backgroundSize: "cover",width: 300,height: 400,justifyItems: 'center',margin: '0 auto', color: 'white', display: 'flex', alignItems: 'end', overflow: "hidden", cursor:'pointer'}}>
                <div style={{backgroundColor: 'grey', width: '100%', padding: '20px 50px'}}>
                  <h1>{e.Title}</h1>
                  <p>{e.Year}</p>
                  {/* <img src={e.Poster}/> */}
                </div>
              </div>
            )
          })

          }
        </section>
      </main>
    </>
  )
}
